services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: accessmate-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: accessmate_ai

    expose:
      - "5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: accessmate-backend
    restart: unless-stopped

    env_file:
      - backend/.env

    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@postgres:5432/accessmate_ai

    depends_on:
      - postgres

    expose:
      - "8000"


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: accessmate-frontend
    restart: unless-stopped

    depends_on:
      - backend

    expose:
      - "80"



  caddy:
    image: caddy:2-alpine
    container_name: accessmate-caddy
    restart: unless-stopped

    depends_on:
      - frontend

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config


volumes:

  postgres_data:
  caddy_data:
  caddy_config:
